config/routes.rb
FinalProject::Application.routes.draw do

  resources :favorites, :only => [:create]

  resources :categories, :only => [:index, :new, :create, :edit, :update, :destroy]

  resources :users, :only => [:index, :create, :show, :edit, :update]
  
  resources :sessions, :only => [:index, :create, :destroy]

  resources :recipebox, :only => [:index, :create, :show, :edit, :destroy]
  
  resources :cookbooks do
    collection { get :stream }
  end

  resources :comments, :only => [:create]

  resources :friendsbox, :only => [:index, :show]

  resources :friends, :only => [:index, :new, :create, :update, :destroy]

  resources :recipes, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

  get "/signin" => 'sessions#index', :as => :login

  get "/signout" => 'sessions#destroy', :as => :logoff

  get "/cookbooks/index" => 'cookbooks#index'

  root 'sessions#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
  before_action :require_login

  def index
  	@friends = Friend.includes(:user).where("(user_id = ? AND status = 'confirm') OR (friend_id = ? AND status = 'pending')", session[:user_id], session[:user_id])
  	@friend = Friend.new
  end

  def new
  	@addfriend = Friend.new
  	if (params.has_key?(:first_name) && params.has_key?(:last_name) && params.has_key?(:email))
	  	if params[:first_name] != "" || params[:last_name]
	  		@friendsearch =User.where("first_name = ? OR last_name = ?", params[:first_name], params[:last_name]) 
	  		render :new
	  	else
	  		@friendsearch =User.where("email = ?", params[:email]) 
	  		render :new
	  	end
	  end
  end

  def create
  	@friend = Friend.new(friend_params)
  	if @friend.save
  		redirect_to friends_path
  	else
  		render :new
  	end
  end

  def update
  	@friend = Friend.find(params[:id])
    if @friend.update(friend_params)
  	   @friend2 = Friend.new(user_id: @friend.friend_id, friend_id: @friend.user_id, status: "confirm")
       if @friend2.save
  	     redirect_to friends_path
       end
    end
  end

  def destroy
  	@friend = Friend.find(params[:id])
  	@friend.destroy
    redirect_to friends_path
  end

  def require_login
    unless signed_in?
      deny_access
    end
  end

  private
  def friend_params
  	params.require(:friend).permit(:user_id, :friend_id, :status)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper

	def pending(user_id)
		@friends_pending = Friend.where("(friend_id = ? AND status = 'pending')", user_id).count
	end
	
end

app/views/friends/index.html.erb
<h4><%= current_user.first_name %>'s Friends</h4>
<%= button_to "Add a Friend", new_friend_path, :class => 'success button right', :method => :get %>
<table>
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% if @friends %>
			<% @friends.each do |friend| %>
				<tr>
					<td><%= friend.user.first_name %></td>
					<td><%= friend.user.last_name %></td>
					<td>
						<% if friend.status == "pending" %>
							<%= form_for @friend, :url => friend_path(friend.id), :method => :put do |f| %>
								<%= f.hidden_field :status, :value => "confirm" %>
								<div class='button-group'>
									<span class='button small disabled secondary'>PENDING</span>
								<%= f.submit "Confirm Friend", :class => "small button success" %>
								</div>
							<% end %>
						<% end %>
						<% if friend.status == "confirm" %>
							<a href="#" data-reveal-id="friend<%= friend.id %>"><button class="small button alert" >Un-friend</button></a>
						<% end %>
					</td>
				</tr>
				<div id="friend<%= friend.id %>" class="reveal-modal" data-reveal>
				  <h2>Are you sure you want to remove this friend?</h2>
				  <p>Once <%= friend.user.first_name %> is un-friended you will have to go through the friending process again.</p>
				  <%= button_to "Delete", friend_path(friend.id), :method=>:delete, :class => "large button alert right" %>
				  <a class="close-reveal-modal">&#215;</a>
				</div>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/friends/new.html.erb
<h4>Find a friend</h4>
<%= form_tag new_friend_path, :method => :get do %>
	<h6>Find by Name</h6>
	<%= label_tag :first_name %>
	<%= text_field_tag :first_name %>
	<%= label_tag :last_name %>
	<%= text_field_tag :last_name %>
	<h6>Find by E-mail</h6>
	<%= label_tag :email %>
	<%= text_field_tag :email %>
	<%= submit_tag :Find, :class=>"button right" %>
<% end %>

<% if @friendsearch %>
	<table>
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @friendsearch.each do |friend| %>
				<tr>
					<td><%= friend.first_name %></td>
					<td><%= friend.last_name %></td>
					<td>
						<%= form_for @addfriend do |f| %>
							<%= f.hidden_field :user_id, :value =>current_user.id %>
							<%= f.hidden_field :friend_id, :value => friend.id %>
							<%= f.hidden_field :status, :value => "pending" %>
							<%= f.submit "Add Friend", :class => "small button success" %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>