config/routes.rb
FinalProject::Application.routes.draw do

  resources :favorites, :only => [:create]

  resources :categories, :only => [:index, :new, :create, :edit, :update, :destroy]

  resources :users, :only => [:index, :create, :show, :edit, :update]
  
  resources :sessions, :only => [:index, :create, :destroy]

  resources :recipebox, :only => [:index, :create, :show, :edit, :destroy]
  
  resources :cookbooks do
    collection { get :stream }
  end

  resources :comments, :only => [:create]

  resources :friendsbox, :only => [:index, :show]

  resources :friends, :only => [:index, :new, :create, :update, :destroy]

  resources :recipes, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

  get "/signin" => 'sessions#index', :as => :login

  get "/signout" => 'sessions#destroy', :as => :logoff

  get "/cookbooks/index" => 'cookbooks#index'

  root 'sessions#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :categories
	has_many :recipes
	has_many :recipes, through: :recipe_box
	has_many :recipeboxes
	has_many :favorites
	has_many :friends
	has_many :comments

	attr_accessor :password, :password_confirmation

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name,    :presence   => true,
	          :format               => { :with => /\A([A-Za-z\s]*)\z/i}
	
	validates :last_name,    :presence   => true,
	          :format               => { :with => /\A([A-Za-z\s]*)\z/i}
	
	validates :email,   :presence   => true,
	          :format               => { :with => email_regex },
	          :uniqueness           => { :case_sensitive => false }
	validates :password,  :presence => true,
	          :confirmation         => true,
	          :length               => { :within => 4..100 }

	before_save :encrypt_password


	def has_password?(submitted_password)
	  self.encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
	  user = find_by_email(email)
	  return nil if user.nil?
	  return user if user.has_password?(submitted_password)
	end


	private
	  def encrypt_password
	    self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
	    self.encrypted_password = encrypt(self.password)
	  end

	  def encrypt(pass)
	    Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	before_action :require_login, except: :create

  def index
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  	  sign_in @user
  	  redirect_to recipes_path
  	else
  	  flash[:errors] = @user.errors.full_messages
      redirect_to :back
  	end
  end

  def show
  	@subtitle = @current_user.first_name + "'s Information"
  end

  def edit
  	@subtitle = "Edit User Information"
  	@user = @current_user
  end

  def update
  	@user = @current_user
  	if @user.update(user_params)
  	  redirect_to user_path(current_user.id)
  	else
  	  redirect_to :back
  	end
  end

  def require_login
    unless signed_in?
      deny_access
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h4>Edit <%= current_user.first_name %>'s User Information</h4>
<%= form_for @user do |f| %>
  <% if flash[:errors] %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('#newuserpanel').click()
        return false
      })
    </script>
  <div id="error_explanation" class='alert-box warning radius'>
      <ul>
      <% flash[:errors].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %> 
  <%= f.label :password %>
  <%= f.password_field :password %> 
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Update Account", :class => 'button' %>
<% end %>

app/views/users/index.html.erb
<h4>User Setting</h4>
<ul>
	<li><%= link_to "Show user information", user_path(current_user.id)  %></li>
	<li><%= link_to "Your friends list", friends_path %></li>
	<li><%= link_to "Edit your categories", categories_path %></li>
</ul>

app/views/users/show.html.erb
<h4><%= current_user.first_name %>'s User Information</h4>
<table>
	<tbody>
		<tr>
			<td>First Name</td>
			<td><%= current_user.first_name %></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><%= current_user.last_name %></td>
		</tr>
		<tr>
			<td>E-mail</td>
			<td><%= current_user.email %></td>
		</tr>
	</tbody>
</table> 
<%= link_to "Edit your information", edit_user_path(current_user.id) %>