config/routes.rb
FinalProject::Application.routes.draw do

  resources :favorites, :only => [:create]

  resources :categories, :only => [:index, :new, :create, :edit, :update, :destroy]

  resources :users, :only => [:index, :create, :show, :edit, :update]
  
  resources :sessions, :only => [:index, :create, :destroy]

  resources :recipebox, :only => [:index, :create, :show, :edit, :destroy]
  
  resources :cookbooks do
    collection { get :stream }
  end

  resources :comments, :only => [:create]

  resources :friendsbox, :only => [:index, :show]

  resources :friends, :only => [:index, :new, :create, :update, :destroy]

  resources :recipes, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

  get "/signin" => 'sessions#index', :as => :login

  get "/signout" => 'sessions#destroy', :as => :logoff

  get "/cookbooks/index" => 'cookbooks#index'

  root 'sessions#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :recipes, through: :recipe_categories
  has_many :recipe_categories

  validates :category,    		:presence   => true,
	          :format               		=> { :with => /\A([A-Za-z\s]*)\z/i}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_login
  
  def index
    @subtitle = "Managing Categories"
    @categories = current_user.categories.all.order('category')
  end

  def new
    @subtitle = "Managing Categories"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @subtitle = "Managing Categories"
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def require_login
    unless signed_in?
      deny_access
    end
  end

  private
  def category_params
    params.require(:category).permit(:user_id, :category)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h4>Edit Categories</h4>
<% if @category.errors.any? %>
	<div id="error_explanation" class='alert-box warning radius'>
	  <h2><%= pluralize(@category.errors.count, "error") %> prevented the product from being created:</h2>
	  <ul>
	    <% @category.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>
<%= form_for @category do |f| %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.text_field :category %>
	<%= f.submit "Update Category", :class => :button %>
<% end %>

app/views/categories/index.html.erb
		<h4><%= current_user.first_name %>'s Category List</h4>
		<%= button_to "Add a Category", new_category_path, :class => 'success button right', :method => :get %>
		<table>
			<thead>
				<tr>
					<th>Category</th>
					<th col_span='2'>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% if @categories %>
					<% @categories.each do |category| %>
						<tr>
							<td><%= category.category %></td>
							<td>
								<div class='button-group radius'>
									<%= button_to "Edit", edit_category_path(category.id), :class => "small button", :method => :get %>
									<a href="#" data-reveal-id="modal<%= category.id %>"><button class="small button alert" >Delete</button></a>
								</div>
								<div id="modal<%= category.id %>" class="reveal-modal" data-reveal>
								  <h2>Are you sure you want to delete this category?</h2>
								  <p>Once <%= category.category %> is deleted it can not be reversed.</p>
								  <%= button_to "Delete", category_path(category.id), :method=>:delete, :class => "large button alert right" %>
								  <a class="close-reveal-modal">&#215;</a>
								</div>
							</td>
						</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="content" id="panel2">

	</div>
</div>

app/views/categories/new.html.erb
<h4>New Categories</h4>
<% if @category.errors.any? %>
	<div id="error_explanation" class='alert-box warning radius'>
	  <h2><%= pluralize(@category.errors.count, "error") %> prevented the product from being created:</h2>
	  <ul>
	    <% @category.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>
<%= form_for @category do |f| %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.text_field :category %>
	<%= f.submit "Add Category", :class => :button %>
<% end %>