config/routes.rb
FinalProject::Application.routes.draw do

  resources :favorites, :only => [:create]

  resources :categories, :only => [:index, :new, :create, :edit, :update, :destroy]

  resources :users, :only => [:index, :create, :show, :edit, :update]
  
  resources :sessions, :only => [:index, :create, :destroy]

  resources :recipebox, :only => [:index, :create, :show, :edit, :destroy]
  
  resources :cookbooks do
    collection { get :stream }
  end

  resources :comments, :only => [:create]

  resources :friendsbox, :only => [:index, :show]

  resources :friends, :only => [:index, :new, :create, :update, :destroy]

  resources :recipes, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

  get "/signin" => 'sessions#index', :as => :login

  get "/signout" => 'sessions#destroy', :as => :logoff

  get "/cookbooks/index" => 'cookbooks#index'

  root 'sessions#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :recipes, through: :recipe_categories
  has_many :recipe_categories

  validates :category,    		:presence   => true,
	          :format               		=> { :with => /\A([A-Za-z\s]*)\z/i}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  validates :comment,    		:presence   => true,
            :format               		=> { :with => /\A([A-Za-z\s\d\D]*)\z/i}

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user

  has_many :recipes
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

  validates :name,    		:presence   => true,
	          :format               		=> { :with => /\A([A-Za-z\s]*)\z/i}
	
	validates :quantity, 		:presence		=> true,
						:format     => { :with => /\A([A-Za-z\s]*)\z/i }

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  require 'pg'

	# after_save :notify_recipe_addition

	belongs_to :users

	has_many :categories, through: :recipe_categories
	has_many :users, through: :recipe_boxes
	has_many :users, through: :favorites
	has_many :recipe_boxes
	has_many :recipe_categories
	has_many :recipes
	has_many :favorites
	has_many :comments

	scope :title, -> (recipeTitle) { where("title LIKE ?", "%#{recipeTitle}%") }
	scope :category, -> (recipeCategory) { where(:category_id => recipeCategory) }
	scope :favorite, -> (favorite, current_user) { where("favorite = ? AND user_id = ?", favorite, current_user) }

	attr_accessor :image, :category, :favorite

	validates :title,    		:presence   => true,
	          :format               		=> { :with => /\A([A-Za-z\W\s]*)\z/i}
	
	validates :description, :format     => { :with => /\A([A-Za-z\W\s]*)\z/i}
	
	has_attached_file :image, :styles 	=> { :medium => "300x300>", :thumb => "100x100>" }, 
														:default_url => "/imagesç/:style/missing.jpg"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  validates :yield,   		:format     => { :with => /\A([\dA-Za-z\s]*)\z/i }
  
  validates :actual_time, :allow_blank => true,
  					:format			=> { :with => /\d*[:]\d\d/, :message => "Please enter times in HH:MM format. "}

  validates :total_time, 	:allow_blank => true,
  					:format			=> { :with => /\d*[:]\d\d/, :message => "Please enter times in HH:MM format. "}

  validates :source, 			:format			=> { :with => /\A([\dA-Za-z\s]*)\z/i }

  validates :instructions,:presence		=> true

  # def notify_recipe_addition
  #    connection.execute "NOTIFY #{:channel}"
  # end

  # cnf = YAML::load_file(File.join(__dir__, '/config/database.yml'))

  # if Rails.env.development?
  #   conn = PG.connect( :dbname => 'recipebox_development', :user => cnf[:development][:user], :password => cnf[:development][:password] )
  # elsif Rails.env.test?
  #   conn = PG.connect( :dbname => 'recipebox_test' )
  # else
  #   conn = PG.connect( :dbname => 'recipebox_production' )
  # end

  TRIGGER_TABLE = %{
    CREATE TABLE IF NOT EXISTS recipes(message text);
  }

  TRIGGER_FUNCTION = %{
  CREATE OR REPLACE FUNCTION notify_recipe_addition() RETURNS TRIGGER LANGUAGE plpgsql
  AS $$
      BEGIN
          NOTIFY cookbooks;
          RETURN NULL;
      END
  $$
  }

  DROP_TRIGGER = %{
  DROP TRIGGER IF EXISTS notify_trigger ON recipes
  }

  TRIGGER = %{
  CREATE TRIGGER notify_trigger AFTER INSERT ON recipes FOR EACH STATEMENT EXECUTE PROCEDURE notify_recipe_addition();
  }

  connection.execute( TRIGGER_TABLE )
  connection.execute( TRIGGER_FUNCTION )
  connection.execute( DROP_TRIGGER )
  connection.execute( TRIGGER )

  def self.on_recipe_add
    connection.execute( 'LISTEN cookbooks' )
    loop do
      connection.raw_connection.wait_for_notify do |cookbooks, pid, recipe|
        yield recipe
      end
    end
  ensure
    connection.execute "UNLISTEN cookbooks"
  end

end

app/models/recipe_box.rb
class RecipeBox < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe_category.rb
class RecipeCategory < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :categories
	has_many :recipes
	has_many :recipes, through: :recipe_box
	has_many :recipeboxes
	has_many :favorites
	has_many :friends
	has_many :comments

	attr_accessor :password, :password_confirmation

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name,    :presence   => true,
	          :format               => { :with => /\A([A-Za-z\s]*)\z/i}
	
	validates :last_name,    :presence   => true,
	          :format               => { :with => /\A([A-Za-z\s]*)\z/i}
	
	validates :email,   :presence   => true,
	          :format               => { :with => email_regex },
	          :uniqueness           => { :case_sensitive => false }
	validates :password,  :presence => true,
	          :confirmation         => true,
	          :length               => { :within => 4..100 }

	before_save :encrypt_password


	def has_password?(submitted_password)
	  self.encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
	  user = find_by_email(email)
	  return nil if user.nil?
	  return user if user.has_password?(submitted_password)
	end


	private
	  def encrypt_password
	    self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
	    self.encrypted_password = encrypt(self.password)
	  end

	  def encrypt(pass)
	    Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper

@title = "RecipeBox"

def random_background
  images = ["brownies.jpg", "cake.jpg", "cookies.jpg", "pasta.jpg", "sandwich.jpg", "spaghetti.jpg", "steak.jpg", "salad.jpg"]
  images[rand(images.size)]
end

def controller?(*controller)
	controller.include?(params[:controller])
end

def action?(*action)
	action.include?(params[:action])
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper

	def pending(user_id)
		@friends_pending = Friend.where("(friend_id = ? AND status = 'pending')", user_id).count
	end
	
end

app/helpers/friendsbox_helper.rb
module FriendsboxHelper
end

app/helpers/recipebox_helper.rb
module RecipeboxHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	
	def headerSplit(content)
		content.slice!("{")
		content.slice!("}")
		return content
	end

	def headerTest(content)
		if content[0,1]=="{"
			return TRUE
		else
			return FALSE
		end
	end

	def letterTest(content)
		alphabet = ('a'..'z').to_a
		if alphabet.include?(content[0,1].downcase)
			return TRUE
		else
			return FALSE
		end
	end

	def newLineSplit(content)
		return content.split(/\r\n/)
	end

	def spaceSplit(content)
		return content.split(" ", 2)
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
	  session[:user_id] = user.id
	  self.current_user=(user)
	end
	
	def current_user=(user)
	  @current_user = user
	end

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
	  !current_user.nil?
	end

	def sign_out
	  session[:user_id] = nil
	  self.current_user = nil
	end

	def current_user?(user)
	  user == self.current_user 
	end

	def deny_access
	  redirect_to login_path, :notice => "Please sign in to access this page."
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeBox - <%= @subtitle %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'vendor/modernizr', params[:controller] %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  	#container{
  		background-image: url("<%= asset_path("backgrounds/" + random_background) %>");
  	}
  </style>
</head>
  <body>
    <div id='wrapper'>
    	<div id='container'>
    		<div id='body'>
    			<div class="fixed">
    			  <nav class="top-bar" data-topbar role="navigation">
    			    <section class="top-bar-section">
    			      <!-- Left Nav Section -->
    			      <% if signed_in? %>
      			      <ul class="left">
      			        <li class=<% if controller?("recipes") && action?("index", "show", "edit") %>"active disabled"<%end%> ><a href="/recipes">My Recipes</a></li>
                    <li class=<% if controller?("recipebox") && action?("index", "show", "edit") %>"active disabled"<%end%>><a href="/recipebox">My Recipe Box</a></li>
      			        <li class=<% if controller?("friendsbox") && action?("index", "show") %> "active disabled"<%end%>><a href="/friendsbox">Friend's Recipes</a></li>
      			        <li class="divider"></li>
      			        <!-- <li class=<% if controller?("friendsbox") && action?("index disabled", "show") %> "active disabled"<%end%>><a href="/cookbook">Explore the Cookbook</a></li> -->
      			      </ul>
      			    <% end %>
    			      <!-- Right Nav Section -->
    			      <ul class="right">
    			      	<% if signed_in? %>
                    <% if pending(current_user.id) > 0 %>
                      <li class='white'>Notfications<span id='notifications'><%= link_to pending(current_user.id), friends_path %></span></li>
                    <% end %>
    			        <li class="has-dropdown" class=<% if controller?("user", "friends") && action?("index", "show", "edit") %> "active"<%end%>>
    			          <a href="/users">User Account</a>
    			          <ul class="dropdown">
    			            <li class=<% if controller?("user") && action?("show", "edit") %> "active disabled"<%end%>><a href="/users/<%= current_user.id %>">Show Account Information</a></li>
    			            <li class=<% if controller?("friends") && action?("index") %> "active disabled"<%end%>><a href="/friends">Find Friends<% if pending(current_user.id) > 0 %><div id='notifications' class='label secondary'><%= pending(current_user.id) %></div><% end %></a></li>
                      <li class=<% if controller?("user") && action?("show", "edit") %> "active disabled"<%end%>><a href="/users">Edit Settings</a></li>
    			          </ul>
    			        </li>
    			        <% end %>
    			        <% if signed_in? %>
      			        <li class="has-form">
      			           <%= link_to('Log-out', logoff_path, :class => "button secondary") %>
      			        </li>
                  <% else %>
                  	<li class="has-form">
                      <a href="#" id='login' class='button secondary'>Log-in</a>
    			        	</li>
                <% end %>
    			      </ul>
    			    </section>
    			  </nav>
    			</div>
    			<div id='title'>
    				<h1>RecipeBox</h1>
    				<h4><%= @subtitle %></h4>
    			</div>
    			<div id='content'>
    				<%= yield %>
    			</div>
    		</div>
    	</div>
    </div>
  <%= javascript_include_tag "application" %>
    <script>
      (function(i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r;
          i[r] = i[r] || function() {
              (i[r].q = i[r].q || []).push(arguments)
          }, i[r].l = 1 * new Date();
          a = s.createElement(o),
              m = s.getElementsByTagName(o)[0];
          a.async = 1;
          a.src = g;
          m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-55360839-1', 'auto');
      ga('require', 'linkid', 'linkid.js');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    </script>
</body>
</html>